### ISSUE TITLE
Expose datapoints for water stove

### ISSUE THREAD

**Issue by benlbrm** [benlbrm/hottohpy#1]
Mine is a water stove, and the application allows these parameters to be displayed/controlled:

- In the main screen:

![image](https://user-images.githubusercontent.com/36958524/142934664-b4f5ed0d-d702-433f-aa7c-237e7c25d959.png)

- [x] In the upper left corner there is an icon indicating whether the water pump is running or not.

- [X] In the middle there is an icon indicating the current status. This is already exposed, however, I have seen the following:  

  When the pellets are running out, the cooker makes a beep. However, neither the app icon nor the home assistant "action" entity change, it is kept on "heating".
  If the stove is switched off due to lack of pellets, then yes, the entity "action" changes to "stopping" and then to "end pellet".
  I don't know if it would be possible  to read an extra status indicating "low pellet". But it would be a very useful feature, to be able to notify about the lack of pellets via home assistant.

- [X] Below the icon, it shows the current environment temperature, which is already exposed.

- [x] Finally, the water temperature is displayed. I guess it corresponds to the index #17 of your screenshot. 

- In the status screen:

![image](https://user-images.githubusercontent.com/36958524/142936491-e392956a-e917-4f84-be8e-77bd89455ef8.png)

- [x] Firstly, the power at which the stove is operating. Guess it is parameter #22.

- [X] Set and Environment, already exposed.

- [x] Water temperature, the same as shown in the main screen.

- [X] Fumes temperature, already exposed.

- [X] Fumes fan speed, already exposed. As you see in the snapshot, the unit seems to be g/m and not rpm. But not sure if this is correct in the app.

- [x] Last one, air exchanger fan speed. This is not exposed and I think it must be #27, #30 or #33.

- In the control screen:

![image](https://user-images.githubusercontent.com/36958524/142937735-124efa92-4e1f-43b3-b501-34592c4dff84.png)

- [X] Firstly, the Eco mode, already exposed. I really don't know if it has any real effect on my stove.

- [ ] Next, the Chrono mode, not exposed. For me it is secondary, because thanks to the integration, it will be possible to schedule the stove using home assistant.
- [ ] Next, the programmed power. I don't know how it behaves because the stove adjusts this value automatically according to the temperatures. It's not exposed but I guess it is #23.
- [X] Next, the environment setpoint. Already exposed.

- [x] Last, and very important In my opinion, the air exchanger fan speed. I can change it from 0 - 5 and "Auto".  I suppose it will be #28, #31 or #34.

As you can see, the app does not let you adjust the water temperature setpoint. But, according to your screenshots, I think it is possible to adjust it using parameter #18. This would be very very useful in my opinion, especially because it is not possible from the app.

I'm sorry for rambling, It is not my intention to give you so much work, only that you know which parameters are interesting in the case of water stoves.

Feel free to move this to a new issue or enhancement (or six, or seven ;) ). This is probably not the best place to discuss it.

_Originally posted by @elkarto in https://github.com/benlbrm/ha-hottoh-component/issues/1#issuecomment-975950970_

**Comment by benlbrm** [comment]
@elkarto
Can you run the example.py on the hottohpy lib standalone and give me the output you will get ?
On last commit, I've output all datapoints I can have from the wifi module

**Comment by elkarto** [comment]
That's done!

#### Start Stove Data's ####
_getFirmwareVersion: %s 6.2.41
_getWifiSignal: %s nosig
_getPageIndex: %s b'#00000A---0062DATR0
_getManufacturer: %s EdilKamin
_getIsBitmapVisible: %s 0
_getIsValid: %s 1
_getStoveType: %s 23
_getStoveState: %s switched_off
_getStoveIsOn: %s off
_getEcoMode: %s off
_getChronoMode: %s off
_getTemperatureRoom1: %s 19.5
_getSetTemperatureRoom1: %s 29.1
_getSetMaxTemperatureRoom1: %s 40.0
_getSetMinTemperatureRoom1: %s 5.0
_getTemperatureRoom2: %s -43.5
_getSetTemperatureRoom2: %s 0.0
_getSetMaxTemperatureRoom2: %s 0.0
_getSetMinTemperatureRoom2: %s 0.0
_getTemperatureWater: %s 24.0
_getSetTemperatureWater: %s 73.0
_getSetMaxTemperatureWater: %s 80.0
_getSetMinTemperatureWater: %s 55.0
_getSmokeTemperature: %s 20.2
_getPowerLevel: %s 0
_getSetPowerLevel: %s 100
_getSetMaxPowerLevel: %s 100
_getSetMinPowerLevel: %s 1
_getSpeedFanSmoke: %s 0
_getSpeedFan1: %s 3
_getSetSpeedFan1: %s 3
_getSetMaxSpeedFan1: %s 5
_getSpeedFan2: %s 1
_getSetSpeedFan2: %s 1
_getSetMaxSpeedFan2: %s 0
_getSpeedFan3: %s 0
_getSetSpeedFan3: %s 0
_getSetMaxSpeedFan3: %s 0
_getFlowSwitch: %s 1
_getGenericPump: %s 0
_getAirEx1: %s 0
_getAirEx2: %s 0
_getAirEx3: %s 0
_getPuffer: %s -435
_getSetPuffer: %s 500
_getSetMinPuffer: %s 200
_getSetMaxPuffer: %s 750
_getBoiler: %s -435
_getSetBoiler: %s 500
_getSetMinBoiler: %s 100
_getSetMaxBoiler: %s 700
_getDhw: %s 0
_getSetDhw: %s 750
_getSetMinDhw: %s 500
_getSetMaxDhw: %s 800
_getDhw: %s 0
_getSetDhw: %s 750
_getSetMinDhw: %s 500
_getSetMaxDhw: %s 800
_getRoomTemp3: %s -435
_getSetRoomTemp3: %s 0
_getSetMinRoomTemp3: %s 0
_getSetMaxRoomTemp3: %s 0
#### End Stove Data's ####


I was doing my tests to get the values, as a python exercise, but you are going much faster than me.

**Comment by elkarto** [comment]
As you can see, the stove is not running now. I think I'm going to switch it on around 7PM. 

I can post new values when it starts heating.

**Comment by benlbrm** [comment]
yeah cool !
Let me know tonight, maybe we will have more data's available when it's running

**Comment by elkarto** [comment]
No problem, tonight I give you as much information as I can.


May I ask where you have got any documentation to be able to get this working?
Or did you use the jeedom code as a base?

I' m asking because, as I told you, I was working on integrating the stove using modbus, and I couldn't find any information. 
I had to analyze the serial communication stream and see what registers it was reading/writing.
I have a chart of the registers that the wifi module reads/writes from the stove. I don't know if it can be useful for this library.

**Comment by benlbrm** [comment]
You're right, I got the data's from the jeedom plugin, I don't know where the guy from jeedom get's all data's at first.
I think your chart can always be useful

**Comment by benlbrm** [comment]
Can you give a try with the new lib version and new example.py ?
I've find some "stove options" that we can output to check if sensors are availabe.

**Comment by elkarto** [comment]
Here is it.

#### Start Stove Data's ####
Info: %s ["b'#00000A---0014INFRHOTTOH", '6.2.41', 'nosig', "F23E\\n'"]
Info: %s ["b'#00000A---0062DATR0", '85', '0', '1', '23', '0', '0', '0', '0', '181', '291', '50', '400', '-435', '0', '0', '0', '191', '730', '550', '800', '171', '0', '100', '1', '100', '0', '3', '3', '5', '1', '1', '0', '0', '0', '0', "CF15\\n'"]
Info: %s ["b'#00000A---0047DATR2", '1', '0', '0', '0', '0', '-435', '500', '200', '750', '-435', '500', '100', '700', '0', '750', '500', '800', '-435', '0', '0', '0', "12AB\\n'"]       
_getFirmwareVersion: %s 6.2.41
_getWifiSignal: %s nosig
_getPageIndex: %s b'#00000A---0062DATR0
_getManufacturer: %s EdilKamin
_getIsBitmapVisible: %s 0
_getIsValid: %s 1
_getStoveType: %s 23
_getStoveType Binary: %s 10111
_getStoveState: %s switched_off
_getStoveIsOn: %s off
_getEcoMode: %s off
_getChronoMode: %s off
_getTemperatureRoom1: %s 18.1
_getSetTemperatureRoom1: %s 29.1
_getSetMaxTemperatureRoom1: %s 40.0
_getSetMinTemperatureRoom1: %s 5.0
_getTemperatureRoom2: %s -43.5
_getSetTemperatureRoom2: %s 0.0
_getSetMaxTemperatureRoom2: %s 0.0
_getSetMinTemperatureRoom2: %s 0.0
_getTemperatureWater: %s 19.1
_getSetTemperatureWater: %s 73.0
_getSetMaxTemperatureWater: %s 80.0
_getSetMinTemperatureWater: %s 55.0
_getSmokeTemperature: %s 17.1
_getPowerLevel: %s 0
_getSetPowerLevel: %s 100
_getSetMaxPowerLevel: %s 100
_getSetMinPowerLevel: %s 1
_getSpeedFanSmoke: %s 0
_getSpeedFan1: %s 3
_getSetSpeedFan1: %s 3
_getSetMaxSpeedFan1: %s 5
_getSpeedFan2: %s 1
_getSetSpeedFan2: %s 1
_getSetMaxSpeedFan2: %s 0
_getSpeedFan3: %s 0
_getSetSpeedFan3: %s 0
_getSetMaxSpeedFan3: %s 0
_getFlowSwitch: %s 1
_getGenericPump: %s 0
_getAirEx1: %s 0
_getAirEx2: %s 0
_getAirEx3: %s 0
_getPuffer: %s -435
_getSetPuffer: %s 500
_getSetMinPuffer: %s 200
_getSetMaxPuffer: %s 750
_getBoiler: %s -435
_getSetBoiler: %s 500
_getSetMinBoiler: %s 100
_getSetMaxBoiler: %s 700
_getDhw: %s 0
_getSetDhw: %s 750
_getSetMinDhw: %s 500
_getSetMaxDhw: %s 800
_getDhw: %s 0
_getSetDhw: %s 750
_getSetMinDhw: %s 500
_getSetMaxDhw: %s 800
_getRoomTemp3: %s -435
_getSetRoomTemp3: %s 0
_getSetMinRoomTemp3: %s 0
_getSetMaxRoomTemp3: %s 0
Boiler Enabled: %s False
DHW Hot Water Enabled: %s False
Fan number: %s 1
0000000000010111
Pump Enabled: %s False
Temp Room 1 Enabled: %s True
Temp Room 2 Enabled: %s False
Temp Room 3 Enabled: %s False
Temp Water Enabled: %s True
#### End Stove Data's ####


I'll fire the stove in about an hour.

Thank you!!

**Comment by elkarto** [comment]
Sorry for the delay, here is the data with the stove running. 


```
#### Start Stove Data's ####
Info: %s ["b'#00000A---0014INFRHOTTOH", '6.2.41', 'nosig', "F23E\\n'"]
Info: %s ["b'#00000A---0068DATR0", '85', '0', '1', '23', '8', '1', '0', '0', '183', '291', '50', '400', '-435', '0', '0', '0', '548', '730', '550', '800', '1440', '100', '100', '1', '100', '2195', '3', '3', '5', '1', '1', '0', '0', '0', '0', "0534\\n'"]
Info: %s ["b'#00000A---0048DATR2", '1', '1', '76', '0', '0', '-435', '500', '200', '750', '-435', '500', '100', '700', '0', '750', '500', '800', '-435', '0', '0', '0', "7E57\\n'"]      
_getFirmwareVersion: %s 6.2.41
_getWifiSignal: %s nosig                  [[  Don't know why is "no signal", it's connected using wifi ]]
_getPageIndex: %s b'#00000A---0068DATR0
_getManufacturer: %s EdilKamin
_getIsBitmapVisible: %s 0
_getIsValid: %s 1
_getStoveType: %s 23
_getStoveType Binary: %s 10111
_getStoveState: %s power
_getStoveIsOn: %s on
_getEcoMode: %s off
_getChronoMode: %s off
_getTemperatureRoom1: %s 18.3
_getSetTemperatureRoom1: %s 29.1
_getSetMaxTemperatureRoom1: %s 40.0
_getSetMinTemperatureRoom1: %s 5.0
_getTemperatureRoom2: %s -43.5                    [[ not applicable ]]
_getSetTemperatureRoom2: %s 0.0                   [[ not applicable ]]
_getSetMaxTemperatureRoom2: %s 0.0            [[ not applicable ]]
_getSetMinTemperatureRoom2: %s 0.0             [[ not applicable ]]
_getTemperatureWater: %s 54.8
_getSetTemperatureWater: %s 73.0
_getSetMaxTemperatureWater: %s 80.0
_getSetMinTemperatureWater: %s 55.0
_getSmokeTemperature: %s 144.0
_getPowerLevel: %s 100
_getSetPowerLevel: %s 100
_getSetMaxPowerLevel: %s 100
_getSetMinPowerLevel: %s 1
_getSpeedFanSmoke: %s 2195
_getSpeedFan1: %s 3
_getSetSpeedFan1: %s 3
_getSetMaxSpeedFan1: %s 5
_getSpeedFan2: %s 1                                      [[ not applicable ]]
_getSetSpeedFan2: %s 1                                 [[ not applicable ]]
_getSetMaxSpeedFan2: %s 0                          [[ not applicable ]]
_getSpeedFan3: %s 0                                      [[ not applicable ]]
_getSetSpeedFan3: %s 0                                 [[ not applicable ]]
_getSetMaxSpeedFan3: %s 0                          [[ not applicable ]]
_getFlowSwitch: %s 1                                      [[ Don't know which flow switch it refers, I will test with pump off]
_getGenericPump: %s 1                                  [[ Pump status?? I will test with pump off]
_getAirEx1: %s 76
_getAirEx2: %s 0                                              [[ not applicable ]]
_getAirEx3: %s 0                                              [[ not applicable ]]
_getPuffer: %s -435                                         [[ not applicable ]]
_getSetPuffer: %s 500                                     [[ not applicable ]]
_getSetMinPuffer: %s 200                               [[ not applicable ]]
_getSetMaxPuffer: %s 750                               [[ not applicable ]]
_getBoiler: %s -435                                          [[ not applicable ]]
_getSetBoiler: %s 500                                      [[ not applicable ]]
_getSetMinBoiler: %s 100                                [[ not applicable ]]
_getSetMaxBoiler: %s 700                               [[ not applicable ]]
_getDhw: %s 0                                                 [[ not applicable ]]
_getSetDhw: %s 750                                        [[ not applicable ]] 
_getSetMinDhw: %s 500                                  [[ not applicable ]]
_getSetMaxDhw: %s 800                                 [[ not applicable ]]
_getDhw: %s 0                                                 [[ not applicable ]]
_getSetDhw: %s 750                                        [[ not applicable ]]
_getSetMinDhw: %s 500                                  [[ not applicable ]]
_getSetMaxDhw: %s 800                                 [[ not applicable ]]
_getRoomTemp3: %s -435                              [[ not applicable ]]
_getSetRoomTemp3: %s 0                              [[ not applicable ]]
_getSetMinRoomTemp3: %s 0                        [[ not applicable ]]
_getSetMaxRoomTemp3: %s 0                        [[ not applicable ]]
Boiler Enabled: %s False                                  [[ not applicable ]]
DHW Hot Water Enabled: %s False                 [[ not applicable ]]
Fan number: %s 1
0000000000010111                                         [[ I have not seen this changing ]]
Pump Enabled: %s False                                  [[ Pump disabled ?? Don't know which pump is this ]]
Temp Room 1 Enabled: %s True
Temp Room 2 Enabled: %s False
Temp Room 3 Enabled: %s False
Temp Water Enabled: %s True
#### End Stove Data's ####
```
Edit: Fail, the code box font is not monospaced...

I have noted the entries that are not applicable to my particular stove. I assume the stove options you added in the last commit indicate what type of system it is and which entries are applicable.

I have been testing switching the pellet level sensor on and off and have not seen any values that change.
I'm sure the wifi module knows this data (I've seen it reading it from the stove) but maybe it doesn't expose it to the outside.

As soon as I can, I will upload the table with the modbus addresses.

Thank you!!

**Comment by elkarto** [comment]
Another record with the stove stabilized and the level switch off (i.e. Low pellet)
```
#### Start Stove Data's ####
Info: %s ["b'#00000A---0014INFRHOTTOH", '6.2.41', 'nosig', "F23E\\n'"]
Info: %s ["b'#00000A---0066DATR0", '85', '0', '1', '23', '8', '1', '0', '0', '223', '291', '50', '400', '-435', '0', '0', '0', '730', '730', '550', '800', '1220', '1', '100', '1', '100', '1615', '3', '3', '5', '1', '1', '0', '0', '0', '0', "2C30\\n'"]
Info: %s ["b'#00000A---0048DATR2", '1', '1', '76', '0', '0', '-435', '500', '200', '750', '-435', '500', '100', '700', '0', '750', '500', '800', '-435', '0', '0', '0', "7E57\\n'"]      
_getFirmwareVersion: %s 6.2.41
_getWifiSignal: %s nosig
_getPageIndex: %s b'#00000A---0066DATR0
_getManufacturer: %s EdilKamin
_getIsBitmapVisible: %s 0
_getIsValid: %s 1
_getStoveType: %s 23
_getStoveType Binary: %s 10111
_getStoveState: %s power
_getStoveIsOn: %s on
_getEcoMode: %s off
_getChronoMode: %s off
_getTemperatureRoom1: %s 22.3
_getSetTemperatureRoom1: %s 29.1
_getSetMaxTemperatureRoom1: %s 40.0
_getSetMinTemperatureRoom1: %s 5.0
_getTemperatureRoom2: %s -43.5
_getSetTemperatureRoom2: %s 0.0
_getSetMaxTemperatureRoom2: %s 0.0
_getSetMinTemperatureRoom2: %s 0.0
_getTemperatureWater: %s 73.0
_getSetTemperatureWater: %s 73.0
_getSetMaxTemperatureWater: %s 80.0
_getSetMinTemperatureWater: %s 55.0
_getSmokeTemperature: %s 122.0
_getPowerLevel: %s 1
_getSetPowerLevel: %s 100
_getSetMaxPowerLevel: %s 100
_getSetMinPowerLevel: %s 1
_getSpeedFanSmoke: %s 1615
_getSpeedFan1: %s 3
_getSetSpeedFan1: %s 3
_getSetMaxSpeedFan1: %s 5
_getSpeedFan2: %s 1
_getSetSpeedFan2: %s 1
_getSetMaxSpeedFan2: %s 0
_getSpeedFan3: %s 0
_getSetSpeedFan3: %s 0
_getSetMaxSpeedFan3: %s 0
_getFlowSwitch: %s 1
_getGenericPump: %s 1
_getAirEx1: %s 76
_getAirEx2: %s 0
_getAirEx3: %s 0
_getPuffer: %s -435
_getSetPuffer: %s 500
_getSetMinPuffer: %s 200
_getSetMaxPuffer: %s 750
_getBoiler: %s -435
_getSetBoiler: %s 500
_getSetMinBoiler: %s 100
_getSetMaxBoiler: %s 700
_getDhw: %s 0
_getSetDhw: %s 750
_getSetMinDhw: %s 500
_getSetMaxDhw: %s 800
_getDhw: %s 0
_getSetDhw: %s 750
_getSetMinDhw: %s 500
_getSetMaxDhw: %s 800
_getRoomTemp3: %s -435
_getSetRoomTemp3: %s 0
_getSetMinRoomTemp3: %s 0
_getSetMaxRoomTemp3: %s 0
Boiler Enabled: %s False
DHW Hot Water Enabled: %s False
Fan number: %s 1
0000000000010111
Pump Enabled: %s False
Temp Room 1 Enabled: %s True
Temp Room 2 Enabled: %s False
Temp Room 3 Enabled: %s False
Temp Water Enabled: %s True
#### End Stove Data's ####
```

**Comment by benlbrm** [comment]
Wow ! Thank you !
I will definitively do something with that!
Yes you're right, the last options will help to configure sensors to output in Home Assistant.
Keep you in touch in few days

**Comment by elkarto** [comment]
Just a brief remark:

The air exchanger fan has an "Auto" setting.

Although the parameter `_getSetMaxSpeedFan1` is 5. You can set `_getSetSpeedFan1` to value 6, which seems to be "AUTO".

Why all the "max" and "min" parameters are named "_getSet" instead of just "_get"? Can they be modified?

**Comment by benlbrm** [comment]
I have push a new version with new sensors, if you want to give a try.
I've named _getSet because I believe a first that they can be modified by I actually don't know how.

On my case fan1 always give me 0, power_level looks stuck also (wrong registers ?)
AirEx1 is also changing when I change the fan speed on the stove directly, but I don't see the set speed on the lib

**Comment by benlbrm** [comment]
For your pump, is it GenericPump or FlowSwitch ? 
I gess is GenericPump cause in my case, FlowSwitch is set to True and I don't have pump.

For the pellet level, did you see it on the app ?

**Comment by elkarto** [comment]
Here is the data with the last commit.
```
#### Start Stove Data's ####
Info: %s ["b'#00000A---0014INFRHOTTOH", '6.2.41', 'nosig', "F23E\\n'"]
Info: %s ["b'#00000A---0067DATR0", '85', '0', '1', '23', '8', '1', '0', '0', '201', '291', '50', '400', '-435', '0', '0', '0', '717', '730', '550', '800', '1487', '66', '100', '1', '100', '2063', '3', '3', '5', '1', '1', '0', '0', '0', '0', "5CB5\\n'"]
Info: %s ["b'#00000A---0048DATR2", '1', '1', '76', '0', '0', '-435', '500', '200', '750', '-435', '500', '100', '700', '0', '750', '500', '800', '-435', '0', '0', '0', "7E57\\n'"]      
_getFirmwareVersion: %s 6.2.41
_getWifiSignal: %s nosig
_getPageIndex: %s b'#00000A---0067DATR0
_getManufacturer: %s EdilKamin
_getIsBitmapVisible: %s 0
_getIsValid: %s 1
_getStoveType: %s 23
_getStoveType Binary: %s 10111
_getStoveState: %s power
_getStoveIsOn: %s on
_getEcoMode: %s off
_getChronoMode: %s off
_getTemperatureRoom1: %s 20.1
_getSetTemperatureRoom1: %s 29.1
_getSetMaxTemperatureRoom1: %s 40.0
_getSetMinTemperatureRoom1: %s 5.0
_getTemperatureRoom2: %s -43.5
_getSetTemperatureRoom2: %s 0.0
_getSetMaxTemperatureRoom2: %s 0.0
_getSetMinTemperatureRoom2: %s 0.0
_getTemperatureWater: %s 71.7
_getSetTemperatureWater: %s 73.0
_getSetMaxTemperatureWater: %s 80.0
_getSetMinTemperatureWater: %s 55.0
_getSmokeTemperature: %s 148.7
_getSetPowerLevel: %s 100
_getSetMaxPowerLevel: %s 100
_getSetMinPowerLevel: %s 1
_getSpeedFanSmoke: %s 2063
_getSpeedFan1: %s 3
_getSetSpeedFan1: %s 3
_getSetMaxSpeedFan1: %s 5
_getSpeedFan2: %s 1
_getSetSpeedFan2: %s 1
_getSetMaxSpeedFan2: %s 0
_getSpeedFan3: %s 0
_getSetSpeedFan3: %s 0
_getSetMaxSpeedFan3: %s 0
_getFlowSwitch: %s 1
_getGenericPump: %s 1
_getAirEx1: %s 76
_getAirEx2: %s 0
_getAirEx3: %s 0
_getPuffer: %s -435
_getSetPuffer: %s 500
_getSetMinPuffer: %s 200
_getSetMaxPuffer: %s 750
_getBoiler: %s -435
_getSetBoiler: %s 500
_getSetMinBoiler: %s 100
_getSetMaxBoiler: %s 700
_getDhw: %s 0
_getSetDhw: %s 750
_getSetMinDhw: %s 500
_getSetMaxDhw: %s 800
#### End Stove Data's ####
```

I can confirm that `_getPowerLevel` was working fine. As you can see in previous posts, the value was changing. And it was following the value in the app. Seems to be broken in the last commit.

I don´t know how `_getSetPowerLevel` works. Neither with your library nor the app. Because the stove adjust the power level automatically. So I don´t know if this is like a maximum setpoint, or like a temporal setpoint, or it just ignore it. I have to do some testing on this.
Do you know if this setting is doing something in your stove?

I also confirm that `_getSpeedFan1` is working fine. It is showing the actual value 0-6 correctly.
I haven't tried to change the speed from hottohpy but I guess it will be working. I'll see if I can try it tonight.

These are the readings I'm getting:
![image](https://user-images.githubusercontent.com/36958524/143316581-f9f3e6b0-cf48-423c-829d-4e89557fb9a6.png)

Regarding the pump:
I am completely sure that it is not `_getFlowSwitch`, in the first values I gave you, the stove was off and the reading was 1.
I'm pretty sure it's `_getGenericPump`, but I haven't checked. Maybe tonight when I turn off the stoveI can check it out.

**Comment by elkarto** [comment]
I have tried setting the fan speed from hottohpy and it works like a charm.

hottoh.py
```
    def setSpeedFan1(self, value):
        """Set speed level of Fan 1"""
        try:
            result = self.client.sendCommand(
                parameters=[str(StoveCommands.PARAM_NIVEAU_FAN_1.value), str(value)]
            )
            return result
        except:
            raise 
```

example.py:
```
while True:

    stove.setSpeedFan1(6)
    time.sleep(10)
    print("_getSpeedFan1: %s", stove._getSpeedFan1())
    print("_getAirEx1: %s", stove._getAirEx1())
    time.sleep(10)
    stove.setSpeedFan1(5)
    time.sleep(10)
    print("_getSpeedFan1: %s", stove._getSpeedFan1())
    print("_getAirEx1: %s", stove._getAirEx1())
    time.sleep(10)
    stove.setSpeedFan1(4)
    time.sleep(10)
    print("_getSpeedFan1: %s", stove._getSpeedFan1())
    print("_getAirEx1: %s", stove._getAirEx1())
    time.sleep(10)
    stove.setSpeedFan1(3)
    time.sleep(10)
    print("_getSpeedFan1: %s", stove._getSpeedFan1())
    print("_getAirEx1: %s", stove._getAirEx1())
    time.sleep(10)
    stove.setSpeedFan1(2)
    time.sleep(10)
    print("_getSpeedFan1: %s", stove._getSpeedFan1())
    print("_getAirEx1: %s", stove._getAirEx1())
    time.sleep(10)
    stove.setSpeedFan1(1)
    time.sleep(10)
    print("_getSpeedFan1: %s", stove._getSpeedFan1())
    print("_getAirEx1: %s", stove._getAirEx1())
    time.sleep(10)
    stove.setSpeedFan1(0)
    time.sleep(10)
    print("_getSpeedFan1: %s", stove._getSpeedFan1())
    print("_getAirEx1: %s", stove._getAirEx1())
    time.sleep(10)
```

Output:
```
_getSpeedFan1: %s 6
_getAirEx1: %s 76
_getSpeedFan1: %s 5
_getAirEx1: %s 90
_getSpeedFan1: %s 4
_getAirEx1: %s 83
_getSpeedFan1: %s 3
_getAirEx1: %s 76
_getSpeedFan1: %s 2
_getAirEx1: %s 69
_getSpeedFan1: %s 1
_getAirEx1: %s 62
_getSpeedFan1: %s 0
_getAirEx1: %s 0
```

Edit1: I don't know if some sort of value validation needs to be done on the setSpeedFan1 function. Maybe the try block catches the exception correctly. If not, it should check whether the value is between 0 and 6.

Edit2: I have tried `stove.setSpeedFan1(10)` and nothing happens. No exception output. No changes in the stove. The fan keeps working at last valid speed command.

**Comment by benlbrm** [comment]
Ok good, I will probably provide you something good during the weekend.
Actually from my side, on my stove, set speed for the fan is not working at all.
I can set it on the stove directly and nothing is changing on data's we've got with the lib. I will try to contact Astrel to get details.
It's also not working with the AppFire app....  'crying'

And you're right, the appFire app is using a server in Italy just for proxy the data's from the stove.
Data's are collected only when the app is running, the stove is only "pinging" the server every two seconds. I've spend last night on wireshark to understand their process.

**Comment by elkarto** [comment]
I have been testing by setting the power, but it seems to have no effect on the stove. I think this is normal, because the stove automatically regulates it and it doesn't make much sense to force the value. Does it have any effect on your stove?


Today, when I got home, I noticed that all the home assistant devices were responding very slowly. I attempted to enter the web interface and could not access it.
I managed to get into the logs through SCP, and I've seen a lot of hottohpy messages flooding the log.  (6 hours at a rate of about 5 to 6 messages per second, the file was over 100MB) 
I was not able to copy the exact message, because the viewer crashed and I could not access it any more. I had to restart the home assistant host.
But it was a connection failure and the cause of it was "broken pipe".

If I see it again I will try to copy the exact message.



Thank you for all your work, looking forward for new improvements.

**Comment by benlbrm** [comment]
enjoy the new version

**Comment by elkarto** [comment]
Wow, thank you so much! I'm trying it out right now.

**Comment by benlbrm** [comment]
Can you try again with version 0.0.7 of the component ?
A time out was set a bit too short and can cause unexpected disconnections.

**Comment by elkarto** [comment]
![image](https://user-images.githubusercontent.com/36958524/143683404-89efaba7-ef8c-4c25-a328-2bd04acc92b6.png)

Getting this error with last versions. Both 0.0.7 and 0.0.6.

"The configuration flow could not be loaded."

**Comment by benlbrm** [comment]
Did you restart HA between removing the integration ?
Btw, you don't need to remove the integration when updating it. After restarting HA, changes will be loaded.

**Comment by elkarto** [comment]
This is all that I did:

- Replace all files in custom component folder with 0.0.6 version
- Restart HA

After that, the integration appeared as "not reloaded" and the entities of the previous version appeared as "not available". For a long time. 

- I tried to remove the integration from the GUI in order to add it again. But when I click Remove nothing was happening. 
- I removed all the files inside the custom component folder.
- I restarted HA.
- After restart, the integration still appeared, so I removed it from the GUI, now it worked.
- I restarted HA again.
- I copied all files again in the custom component folder.
- Restarted HA
- Now I tried to add the integration and the error I told you was shown.
- Restart again.
- Try again.
- Remove files.
- Restart.
- Copy 0.0.7 files.
- Restart.
- Add the integration.... Same error.


Between multiple retries I've checked with pip if it was installing the correct version of hottohpy library, and yes.
Also tried removing hottohpy and installing it again. Same result.

**Comment by elkarto** [comment]
It's working!!!
